# Kereas Learning
Here I will work on utilizing some basics in kereas but on my data

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv("/Users/victoria/Documents/me/Creatify/python_scripts/playlists 0-999.csv")

In [6]:
data

name                                             tracks  \
0          Throwbacks  0UaMYEvWZi0ZqiDOoHU3YI 6I9VzXrHxO9rA9A5euc8Ak ...   
1    Awesome Playlist  2HHtWyy5CgaQbC7XSoOb0e 1MYYt7h6amcrauCOoso3Gx ...   
2             korean   74tqql9zP6JjF5hjkHHUXp 4erhEGuOGQgjv3p1bccnpn ...   
3                 mat  4WJ7UMD4i6DOPzyXU5pZSz 1Kzxd1kkjaGX4JZz2CYsXB ...   
4                 90s  4iCGSi1RonREsPtfEKYj5b 5qqabIl2vWzo9ApSC317sa ...   
..                ...                                                ...   
995               old  3Wq1XLo82SODnXJpYHvnyD 709JP07qJbz95uMOLHYlWu ...   
996              Daze  1wZqJM5FGDEl3FjHDxDyQd 7yyRTcZmCiyzzJlNzGC9Ol ...   
997               rap  48zmVAYyyhoWfTDe5pGynC 0srwKuJPH8yBzzFUJMBQM2 ...   
998           Country  4FkgULes13bk2eHrsJg4q9 0vFMQi8ZnOM2y8cuReZTZ2 ...   
999   thinking of you  3rUTBx7gmn1IAAwsrjtnO0 6zYqyOJuyXDOvWJwKkZ8tg ...   

                                               artists  avg_danceability  \
0    2wIVse2owClT7go1WT98tk 26dSoYclwsYLMAKD3tpOr4 ...          0.664077   
1    26bcq2nyj5GB7uRr558iQg 7zdmbPudNX4SQJXnYIuCTC ...          0.492382   
2    7lXgbtBDcCRbfc5f8FhGUL 2e4G04F77jxVuDYo44TCSm ...          0.671062   
3    436sYg6CZhNefQJogaXeK0 436sYg6CZhNefQJogaXeK0 ...          0.514429   
4    40Yq4vzPs9VNUrIBG5Jr2i 2DaxqgrOhkeH0fpeiQq2f4 ...          0.576235   
..                                                 ...               ...   
995  0eUVbl6fC6fVsT7xnkSzVJ 6Tz0QRoe083BcOo2YbG9lV ...          0.597244   
996  2HPaUgqeutzr3jx5a9WyDV 5M0lbkGluOPXLeFjApw8r8 ...          0.661235   
997  1rBxtaN521NYi8Z35G7fUn 5LHRHt1k9lMyONurDHEdrp ...          0.734496   
998  7H6dkUChT5EoOQtUVMg4cN 4xFUf1FHVy696Q1JQZMTRj ...          0.558324   
999  6oFs3qk4VepIVFdoD4jmsy 2vm8GdHyrJh2O2MfbQFYG0 ...          0.541955   

     avg_energy  avg_loudness  avg_acousticness  avg_instrumentalness  \
0      0.781077     -4.891212          0.083674              0.000674   
1      0.695923     -8.107974          0.162227              0.223708   
2      0.692953     -4.875594          0.269100              0.000638   
3      0.620902     -9.618754          0.273514              0.203156   
4      0.650418     -7.634529          0.177189              0.081759   
..          ...           ...               ...                   ...   
995    0.655049     -8.745244          0.235812              0.021555   
996    0.487700     -8.565294          0.338606              0.000016   
997    0.690647     -5.989563          0.084931              0.016670   
998    0.660167     -5.622509          0.264800              0.000169   
999    0.334182    -11.205568          0.614580              0.044998   

     avg_liveness  avg_valence   avg_tempo  
0        0.187087     0.642750  121.157500  
1        0.179344     0.476667  124.987128  
2        0.168894     0.565078  114.595984  
3        0.188278     0.451258  125.547627  
4        0.166524     0.490294  127.725412  
..            ...          ...         ...  
995      0.184354     0.674268  123.098171  
996      0.157359     0.404865  120.064706  
997      0.203448     0.539570  114.652286  
998      0.145799     0.450880  127.872852  
999      0.137882     0.301930  110.969682  

[1000 rows x 11 columns]

### Preprocessing
- Tokenization of string data, followed by token indexing.
- Feature normalization.
- Rescaling the data to small values (in general, input values to a neural network should be close to zero -- typically we expect either data with zero-mean and unit-variance, or data in the [0, 1] range.

In [1]:
# Tokenization of strin data
from tensorflow.keras.layers import TextVectorization

2023-03-08 11:38:20.295210: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
import numpy as np

In [34]:
names = data['name'].tolist()
training_data = np.array(names)

Turning strings into sequences of integer word indices

In [33]:
# Create a TextVectorization layer instance. It can be configured to either
# return integer token indices, or a dense token representation (e.g. multi-hot
# or TF-IDF). The text standardization and text splitting algorithms are fully
# configurable.
vectorizer = TextVectorization(output_mode="int")

# Calling `adapt` on an array or dataset makes the layer generate a vocabulary
# index for the data, which can then be reused when seeing new data.
vectorizer.adapt(training_data)

# After calling adapt, the layer is able to encode any n-gram it has seen before
# in the `adapt()` data. Unknown n-grams are encoded via an "out-of-vocabulary"
# token.
integer_data = vectorizer(training_data)
print(integer_data)

tf.Tensor(
[[ 65   0   0 ...   0   0   0]
 [ 81  11   0 ...   0   0   0]
 [137   0   0 ...   0   0   0]
 ...
 [ 15   0   0 ...   0   0   0]
 [  2   0   0 ...   0   0   0]
 [111  30  20 ...   0   0   0]], shape=(1000, 8), dtype=int64)


### Normalizing Features

In [36]:
from tensorflow.keras.layers import Normalization

In [37]:
# Example image data, with values in the [0, 255] range
training_data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")

normalizer = Normalization(axis=-1)
normalizer.adapt(training_data)

normalized_data = normalizer(training_data)
print("var: %.4f" % np.var(normalized_data))
print("mean: %.4f" % np.mean(normalized_data))

var: 1.0005
mean: 0.0000


### Building models with the Keras Functional API

In [40]:
import keras
from tensorflow.keras import layers

In [39]:
# Define our inputs
inputs = keras.Input(shape=(1, 11))

In [41]:
# After defining your input(s), you can chain layer transformations on top of your inputs, until your final output:
# Apply some convolution and pooling layers

# TODO: will need to determien what I want to do here with my layers

x = training_data

x = layers.Conv2D(filters=32, kernel_size=(3, 3), activation="relu")(x)
x = layers.MaxPooling2D(pool_size=(3, 3))(x)
x = layers.Conv2D(filters=32, kernel_size=(3, 3), activation="relu")(x)
x = layers.MaxPooling2D(pool_size=(3, 3))(x)
x = layers.Conv2D(filters=32, kernel_size=(3, 3), activation="relu")(x)

# Apply global average pooling to get flat feature vectors
x = layers.GlobalAveragePooling2D()(x)

# Add a dense classifier on top
num_classes = 10
outputs = layers.Dense(num_classes, activation="softmax")(x)

In [42]:
# Once you have defined the directed acyclic graph of layers that turns your input(s) into your outputs, instantiate a Model object
model = keras.Model(inputs=training_data, outputs=outputs)


# A New Tutorial
Okay that was somewhat helpful... Let's work on a new tutorial found at https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/ to see what else I can elearn

In [43]:
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [44]:
# load the dataset
dataset = loadtxt('pima-indians-diabetes.csv', delimiter=',')
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]

## Define A Model
Models in Keras are defined as a sequence of layers.

We create a Sequential model and add layers one at a time until we are happy with our network architecture.


The first thing to get right is to ensure the input layer has the correct number of input features. This can be specified when creating the first layer with the input_shape argument and setting it to (8,) for presenting the eight input variables as a vector.


In this example, let’s use a fully-connected network structure with three layers

Fully connected layers are defined using the Dense class. You can specify the number of neurons or nodes in the layer as the first argument and the activation function using the activation argument.

Also, you will use the rectified linear unit activation function referred to as ReLU on the first two layers and the Sigmoid function in the output layer

#### You can piece it all together by adding each layer:

- The model expects rows of data with 8 variables (the input_shape=(8,) argument).
- The first hidden layer has 12 nodes and uses the relu activation function.
- The second hidden layer has 8 nodes and uses the relu activation function.
- The output layer has one node and uses the sigmoid activation function.

In [45]:
model = Sequential()
model.add(Dense(12, input_shape=(8,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

You must specify the loss function to use to evaluate a set of weights, the optimizer used to search through different weights for the network, and any optional metrics you want to collect and report during training.

In this case, use cross entropy as the loss argument. This loss is for a binary classification problems and is defined in Keras as “binary_crossentropy“. You can learn more about choosing loss functions based on your problem here:

## Define a Loss Function

In [46]:
# The adam optimizer is a popular for of gradient descent
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit the Model

These configurations can be chosen experimentally by trial and error. You want to train the model enough so that it learns a good (or good enough) mapping of rows of input data to the output classification. The model will always have some error, but the amount of error will level out after some point for a given model configuration. This is called model convergence.

In [47]:
# fit the keras model on the dataset
# This problem will run for a small number of epochs (150) and use a relatively small batch size of 10.
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 4.0695 - accuracy: 0.5690
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1019 - accuracy: 0.5664
Epoch 3/150
77/77 [==============================] - 0s 4ms/step - loss: 0.9470 - accuracy: 0.5833
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8155 - accuracy: 0.6224
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7540 - accuracy: 0.6302
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7666 - accuracy: 0.6276
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7124 - accuracy: 0.6172
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6946 - accuracy: 0.6510
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6601 - accuracy: 0.6589
Epoch 10/150
77/77 [==============================] - 0s 3ms/step - loss: 0.6654 - accuracy: 0.6484
Epoch 11/

## Evaluate the Model

In [49]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y, verbose=0)
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 76.43


## Make Predictions

In [50]:
# make probability predictions with the model
predictions = model.predict(X)
# round predictions 
rounded = [round(x[0]) for x in predictions]

24/24 [==============================] - 0s 1ms/step


In [51]:
# make class predictions with the model
predictions = (model.predict(X) > 0.5).astype(int)

24/24 [==============================] - 0s 1ms/step
